language: cpp

git:
  depth: 3

os: linux
dist: xenial

stages:
  - compile
  - test

env:
  global:
    - MAKEFLAGS="-j 2"

jobs:
  include:
    - os: linux
      stage: compile
      dist: xenial
      sudo: required
      compiler: gcc
      env:
        - QT_MAJOR=5
        - QT_MINOR=11
        - QT_PATCH=2
      addons:
        apt:
          packages:
            - libglu1-mesa-dev
      before_install:
        - export QT_FULL="${QT_MAJOR}.${QT_MINOR}.${QT_PATCH}"  # ex: 5.11.2
        - export QT_SHORT="${QT_MAJOR}${QT_MINOR}"              # ex: 511
        - sudo add-apt-repository -y ppa:beineri/opt-qt-${QT_FULL}-xenial
        - sudo apt-get update -qq
        - sudo apt-get install -qq qt${QT_SHORT}base qt${QT_SHORT}multimedia
        - sudo apt-get install -qq libpulse-dev
        - sudo ln -s /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 /usr/lib/libOpenCL.so
        - . /opt/qt${QT_SHORT}/bin/qt${QT_SHORT}-env.sh
      script:
        - qmake
        - make
        - xvfb-run make -k check
    - os: osx
      osx_image: xcode10.1
      stage: compile
      compiler: clang
      env:
        # current brew stable is 5.11.2
        - QT_MAJOR=5
      before_install:
        - brew update
        - brew install qt${QT_MAJOR} swift
        - brew link --force qt${QT_MAJOR}
      script:
        - qmake
        - make
        - make -k check
    - os: windows
      stage: compile
      compiler: gcc
      env:
        - QT_VERSION=5.11.2
      before_install:
        - ./scripts/install-qt.sh -d /c/Qt --version ${QT_VERSION} --toolchain win32_mingw53 qtbase qtdeclarative qttools qtscript qtmultimedia
        - mkdir ~/install-qt-tools
        - curl --progress-bar -L -o ~/install-qt-tools/package.7z http://qt.mirror.constant.com/online/qtsdkrepository/windows_x86/desktop/tools_mingw/qt.tools.win32_mingw530/5.3.0-2i686-5.3.0-release-posix-dwarf-rt_v4-rev0.7z >&2
        - 7z x -y -o/c/Qt ~/install-qt-tools/package.7z >/dev/null 2>&1
        - rm -Rf ~/install-qt-tools
        - export PATH=/c/Qt/5.11.2/mingw53_32/bin:$PATH
        - export PATH=/c/Qt/Tools/mingw530_32/bin:$PATH
      script:
        - /c/Qt/${QT_VERSION}/mingw53_32/bin/qmake.exe
        - /c/Qt/Tools/mingw530_32/bin/mingw32-make.exe CXXFLAGS=" -pipe -O2 -fno-keep-inline-dllexport -fPIC -std=gnu++11 -Wall -W -D_REENTRANT -mthreads -DUNICODE -D_UNICODE -DWIN32 -DMINGW_HAS_SECURE_API=1 -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_MULTIMEDIAWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB "
        - /c/Qt/Tools/mingw530_32/bin/mingw32-make.exe -k check

install:
    ./update-mods