language: cpp

git:
  depth: 3

os: linux
dist: xenial

stages:
  - compile
  - test

env:
  global:
    - MAKEFLAGS="-j 2"

jobs:
  include:
    - os: linux
      stage: compile
      dist: xenial
      sudo: required
      compiler: gcc
      env:
        - QT_MAJOR=5
        - QT_MINOR=11
        - QT_PATCH=2
      addons:
        apt:
          packages:
            - libglu1-mesa-dev
      script:
        - qmake -v
        - qmake #-r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC"
        - make
        - xvfb-run make -k check
    - os: osx
      osx_image: xcode10.1
      stage: compile
      compiler: clang
      env:
        # current brew stable is 5.11.2
        - QT_MAJOR=5
      script:
        - qmake
        - make
        - make -k check
    - os: windows
      stage: compile
      compiler: gcc
      env:
        - QT_VERSION=5.11.2
      script:
        - export DOWNLOAD_DIR=`mktemp -d 2>/dev/null || mktemp -d -t 'install-qt-tools'`
        - echo ${DOWNLOAD_DIR}
        - curl --progress-bar -L -o ${DOWNLOAD_DIR}/package.7z https://qt.mirror.constant.com/online/qtsdkrepository/windows_x86/desktop/tools_mingw/qt.tools.win32_mingw530/5.3.0-2i686-5.3.0-release-posix-dwarf-rt_v4-rev0.7z >&2
        - 7z x -y -o/c/Qt ${DOWNLOAD_DIR}/package.7z >/dev/null 2>&1
        - rm -f ${DOWNLOAD_DIR}/package.7z
        - /c/Qt/${QT_VERSION}/mingw53_32/bin/qmake.exe
        - /c/Qt/Tools/bin/mingw32-make.exe -k check

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      export QT_FULL="${QT_MAJOR}.${QT_MINOR}.${QT_PATCH}"  # ex: 5.11.2
      export QT_SHORT="${QT_MAJOR}${QT_MINOR}"              # ex: 511
      sudo add-apt-repository -y ppa:beineri/opt-qt-${QT_FULL}-xenial
      sudo apt-get update -qq
      sudo apt-get install -qq qt${QT_SHORT}base qt${QT_SHORT}multimedia
      sudo apt-get install -qq libpulse-dev
      sudo ln -s /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 /usr/lib/libOpenCL.so
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update
      brew install qt${QT_MAJOR} swift
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      ./scripts/install-qt.sh -d /c/Qt --version ${QT_VERSION} --toolchain win32_mingw53 qtbase qtdeclarative qttools qtscript qtmultimedia
    fi

install:
  - export QT_SELECT=qt${QT_MAJOR}
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      . /opt/qt${QT_SHORT}/bin/qt${QT_SHORT}-env.sh
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew link --force qt${QT_MAJOR}
    fi
    ./update-mods

# script:
#   - qmake -v
#   - qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC"
#   - make
#   # Run with X11 display on Linux as some tests require a Qt app
#   - |
#     if [ "$TRAVIS_OS_NAME" == "linux" ]; then
#       xvfb-run make -k check
#     else
#       make -k check
#     fi
