language: cpp

git:
  depth: 3

os: linux
dist: xenial

stages:
  - compile
  - test

env:
  global:
    - MAKEFLAGS="-j 2"

jobs:
  include:
    - os: linux
      stage: compile
      dist: xenial
      sudo: required
      compiler: gcc
      env:
        - QT_MAJOR=5
        - QT_MINOR=11
        - QT_PATCH=2
      addons:
        apt:
          packages:
            - libglu1-mesa-dev
      script:
        - qmake -v
        - qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC"
        - make
        - xvfb-run make -k check
    - os: osx
      osx_image: xcode10.1
      stage: compile
      compiler: clang
      env:
        # current brew stable is 5.11.2
        - QT_MAJOR=5
      script:
        - qmake -v
        - qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC"
        - make
        - make -k check
    - os: windows
      stage: compile
      compiler: gcc
      env:
        # current brew stable is 5.11.2
        - QT_MAJOR=5
      script:
        - qmake -v
        - qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC"
        - make
        - make -k check

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      export QT_FULL="${QT_MAJOR}.${QT_MINOR}.${QT_PATCH}"  # ex: 5.11.2
      export QT_SHORT="${QT_MAJOR}${QT_MINOR}"              # ex: 511
      sudo add-apt-repository -y ppa:beineri/opt-qt-${QT_FULL}-xenial
      sudo apt-get update -qq
      sudo apt-get install -qq qt${QT_SHORT}base qt${QT_SHORT}multimedia
      sudo apt-get install -qq libpulse-dev
      sudo ln -s /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 /usr/lib/libOpenCL.so
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update
      brew install qt${QT_MAJOR} swift
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      ./scripts/install-qt.sh -d /c/Qt --version 5.11.2 --toolchain win32_mingw53 qtbase qtdeclarative qttools qtscript qtmultimedia
    fi

install:
  - export QT_SELECT=qt${QT_MAJOR}
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      . /opt/qt${QT_SHORT}/bin/qt${QT_SHORT}-env.sh
      ./update-mods
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew link --force qt${QT_MAJOR}
      ./update-mods
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      call ./update-mods.bat
    fi

# script:
#   - qmake -v
#   - qmake -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC"
#   - make
#   # Run with X11 display on Linux as some tests require a Qt app
#   - |
#     if [ "$TRAVIS_OS_NAME" == "linux" ]; then
#       xvfb-run make -k check
#     else
#       make -k check
#     fi
